language: cpp
dist: xenial

compiler:
  - clang

before_install:
  - sudo apt-get install clang git libssl-dev
  - sudo apt-get update -yqq
  - sudo apt-get install -y libboost1.58-dev libboost-system1.58-dev libboost-date-time1.58-dev libboost-random1.58-dev
  - sudo apt-get install -y cmake g++-4.8
script:
  - cmake -D CMAKE_CXX_FLAGS=-std=c++11 .
  - make
  - make install
